Rebuild tmux helper functions and mux files

diff --git a/rcm/zsh/functions b/rcm/zsh/functions
--- a/rcm/zsh/functions
+++ b/rcm/zsh/functions
@@ -25,25 +25,39 @@ l.() {
   ls -ld "${1:-$PWD}"/.[^.]*
 }
 
+bux() {
+  sux dotfiles $HOME/code/dotfiles
+  sux jay $HOME/code/jay
+  sux jonallured.com $HOME/code/jonallured.com
+  sux mli $HOME/code/mli
+  sux monolithium $HOME/code/monolithium
+  sux shrt $HOME/code/shrt
+
+  [ -n "$TMUX" ] && echo "ERROR: Already in tmux session, skipping attach." && return 1
+  tmux attach-session -t dotfiles
+}
+
 mux() {
-  if [ -n "$TMUX" ]; then
-    echo "ERROR: You're already in a tmux session. Nesting tmux sessions is a bad idea."
+  local session_name=$(basename $PWD)
+  local start_directory=$PWD
+  sux $session_name $start_directory
+
+  [ -n "$TMUX" ] && echo "ERROR: Already in tmux session, skipping attach." && return 1
+  tmux attach-session -t $session_name
+}
+
+sux() {
+  local session_name=${1//./-}
+  local start_directory=$2
+
+  if ! tmux has-session -t $session_name &>/dev/null; then
+    tmux new-session -d -s $session_name -c $start_directory
+
+    local config_file=$DOTHOME/tmux/$session_name.mux
+    [ -f $config_file ] || config_file=$DOTHOME/tmux/default.mux
+    tmux set-environment -t $session_name mux_name $session_name
+    tmux source-file $config_file
   fi
-
-  name="$(basename $PWD | sed -e 's/\./-/g')"
-
-  if ! $(tmux has-session -t $name &>/dev/null); then
-    tmux new-session -d -s $name
-
-    conf=$DOTHOME/tmux/$name.mux
-    if [ -f $conf ]; then
-      tmux source-file $conf
-    else
-      tmux source-file $DOTHOME/tmux/default.mux
-    fi
-  fi
-
-  tmux attach-session -t $name
 }
 
 pathlist() {
